### PR TITLE
xgboost 1.5.1 [rebuild for python 3.11/3.12]

### PR DESCRIPTION
**Pull request by ViridianMelody**
xgboost 1.5.1

**Destination channel:** defaults

### Links

- [PKG-5221]
- dev_url (pypi): https://github.com/dmlc/xgboost/tree/v1.5.1
- conda-forge: https://github.com/conda-forge/xgboost-feedstock/blob/main/recipe/meta.yaml
- pypi: https://pypi.org/project/xgboost/1.5.1
- pypi inspector: https://inspector.pypi.io/project/xgboost/1.5.1

### Explanation of changes:

- Increment build number
- Upon approval, I'll set abs.yaml to build without merging to master.

[PKG-5221]: https://anaconda.atlassian.net/browse/PKG-5221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by lorepirri — CHANGES_REQUESTED** [review]
we have a more recent version of `xgboost`, this should merge against a versioned branch!

**Comment by lorepirri** [comment]
@ViridianMelody this goes to defaults, no need for `abs.yaml`

**Comment by skupr-anaconda** [comment]
@ViridianMelody I would try to patch `AutoViML 0.1.800` by relaxing the upper bound of `xgboost`, at least to **<1.7.4**, see  https://github.com/AutoViML/Auto_ViML/blob/9e1fdb07e48d369c80a9366422f5c9bec12d39e3/setup.py#L31. I think it will work fine.
We have all python variants for 1.7.3:
```
xgboost                        1.7.3 py310hca03da5_0  pkgs/main
xgboost                        1.7.3 py311hca03da5_0  pkgs/main
xgboost                        1.7.3 py312hca03da5_0  pkgs/main
xgboost                        1.7.3  py38hca03da5_0  pkgs/main
xgboost                        1.7.3  py39hca03da5_0  pkgs/main
```

**Comment by lorepirri** [comment]
`linux-64` fails with:

```
                   INFO       ['  ERROR (r-xgboost): dso library package file:///upload/linux-64::libxgboost==1.5.1=h6a678d5_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps   
                          statically linked? If that is what you want then add it to `build/ignore_run_exports`)']                                                                                           

```

**Comment by lorepirri** [comment]
@skupr-anaconda `AutoViML 0.1.800` won't work with `xgboost 1.7.3` https://github.com/AnacondaRecipes/autoviml-feedstock/pull/1#issuecomment-2221408287 a simple test makes it fail, while with `xgboost 1.5.1` works (but we do not have py311 and py312)

**Review by lorepirri — COMMENTED** [review]
I rebased to `master-1.5.1`

**Review by lorepirri — APPROVED** [review]

**Comment by lorepirri** [comment]
`win` fails in msys world with
```
bash: ./install-py-xgboost.sh: No such file or directory
```

---

`osx-64` fails
```
INFO   /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_11p3evhbfj/croot/xgboost-split_1720724316822/test_tmp/conda_test_runner.sh: line 3: 26572 Segmentation fault: 11
```
I see a `mkl` somewhere, any attempt in `run_constrained` we could try with:
```
 - blas=*=openblas    # [osx and x86_64]
```

**Comment by JeanChristopheMorinPerso** [comment]
@ViridianMelody @lorepirri I fixed the win-64 and osx-64 builds.

**Comment by ViridianMelody** [comment]
> @ViridianMelody @lorepirri I fixed the win-64 and osx-64 builds.

Thank you!

**Comment by lorepirri** [comment]
Thank you @JeanChristopheMorinPerso this unlocks us

**Pull request merged**
